### ISSUE TITLE
Any plans to update to the newer codegen?

### ISSUE THREAD

**Issue by zoechi** [a14n/dart-js-wrapping#10]
I had a brief look into updating it myself but I didn't have a closer look at code_gen myself yet and dart-js-interop also is not one of my strengths.

I tried to use your google_maps package (which depends on `js_wrapping`) but it depends on an old code_gen package that is not compatible with the current Angular2 version.

**Comment by a14n** [comment]
See #9

I could try to make the update but regarding the new Js-interop features (particullarly dart-lang/sdk#24779) I'm not sure it is worth to hurry.

**Comment by zoechi** [comment]
Hard to tell for as I didn't use code_gen and js myself yet.
