### ISSUE TITLE
Dart Strong mode Issues in : //third_party/dart/js_wrapping/

### ISSUE THREAD

**Issue by akashgandotra** [a14n/dart-js-wrapping#11]
The following strong mode issues were reported for : //third_party/dart/js_wrapping/ 

[error] Missing concrete implementation of getter 'DateTime.microsecond' and getter 'DateTime.microsecondsSinceEpoch' (package:js_wrapping/src/wrapping/js/date_to_datetime_adapter.dart, line 8, col 7)
[error] Invalid override. The type of JsDateToDateTimeAdapter.== ((DateTime) → bool) is not a subtype of DateTime.== ((dynamic) → bool). (package:js_wrapping/src/wrapping/js/date_to_datetime_adapter.dart, line 24, col 13)
[error] Invalid override. The type of JsDateToDateTimeAdapter.== ((DateTime) → bool) is not a subtype of Object.== ((dynamic) → bool). (package:js_wrapping/src/wrapping/js/date_to_datetime_adapter.dart, line 24, col 13)
[error] Could not infer type parameter E, dynamic must be of type Serializable<dynamic>. (package:js_wrapping/src/wrapping/js/typed_js_array.dart, line 8, col 104)
[error] Invalid override. The type of TypedJsArray.add ((E) → void) is not a subtype of ListMixin<dynamic>.add ((dynamic) → void). (package:js_wrapping/src/wrapping/js/typed_js_array.dart, line 37, col 13)
[error] Invalid override. The type of TypedJsArray.addAll ((Iterable<E>) → void) is not a subtype of ListMixin<dynamic>.addAll ((Iterable<dynamic>) → void). (package:js_wrapping/src/wrapping/js/typed_js_array.dart, line 38, col 13)
[error] Invalid override. The type of TypedJsArray.sort (([(E, E) → int]) → void) is not a subtype of ListMixin<dynamic>.sort (([(dynamic, dynamic) → int]) → void). (package:js_wrapping/src/wrapping/js/typed_js_array.dart, line 41, col 13)
[error] Invalid override. The type of TypedJsArray.insert ((int, E) → void) is not a subtype of ListMixin<dynamic>.insert ((int, dynamic) → void). (package:js_wrapping/src/wrapping/js/typed_js_array.dart, line 45, col 13)
[error] Invalid override. The type of TypedJsArray.setRange ((int, int, List<E>, [int]) → void) is not a subtype of ListMixin<dynamic>.setRange ((int, int, Iterable<dynamic>, [int]) → void). (package:js_wrapping/src/wrapping/js/typed_js_array.dart, line 53, col 13)
[error] Could not infer type parameter V, dynamic must be of type Serializable<dynamic>. (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 11, col 102)
[error] Invalid override. The type of TypedJsMap.[] ((String) → V) is not a subtype of Map<String, V>.[] ((Object) → V). (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 22, col 13)
[error] Invalid override. The type of TypedJsMap.remove ((String) → V) is not a subtype of Map<String, V>.remove ((Object) → V). (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 26, col 13)
[error] Invalid override. The type of TypedJsMap.containsValue ((V) → bool) is not a subtype of Map<String, V>.containsValue ((Object) → bool). (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 35, col 13)
[error] Invalid override. The type of TypedJsMap.containsKey ((String) → bool) is not a subtype of Map<String, V>.containsKey ((Object) → bool). (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 36, col 13)
[warning] Unsound implicit cast from (dynamic) → dynamic to (dynamic) → Serializable<dynamic> (package:js_wrapping/src/wrapping/js/typed_js_array.dart, line 8, col 146)
[warning] Unsound implicit cast from dynamic to E (package:js_wrapping/src/wrapping/js/typed_js_array.dart, line 14, col 25)
[warning] Unsound implicit cast from List<dynamic> to List<E> (package:js_wrapping/src/wrapping/js/typed_js_array.dart, line 43, col 36)
[warning] Unsound implicit cast from (dynamic) → dynamic to (dynamic) → Serializable<dynamic> (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 11, col 142)
[warning] Unsound implicit cast from dynamic to V (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 17, col 25)
[warning] Unsound implicit cast from dynamic to Iterable<String> (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 32, col 7)
[warning] Unsound implicit cast from dynamic to V (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 38, col 7)
[warning] Unsound implicit cast from Iterable<dynamic> to Iterable<V> (package:js_wrapping/src/wrapping/js/typed_js_map.dart, line 46, col 39)

**Comment by a14n** [comment]
Fix in 0.3.0
