### ISSUE TITLE
Upgrade source_gen dependency to 0.5

### ISSUE THREAD

**Issue by enyo** [a14n/dart-js-wrapping#8]
This would be great since we aren't able to use `google_maps` otherwise

**Comment by a14n** [comment]
For `google_maps` `source_gen` is only used to generate source files. If you only use `google_maps` you can ignore the `source_gen` dependency by using :

```yaml
dependency_overrides:
  source_gen: 0.5
```

Let me know if it works or not.

**Comment by enyo** [comment]
Great, thanks!

**Comment by enyo** [comment]
If it's only used to build the library, shouldn't they go to `dev_dependencies`?

**Comment by enyo** [comment]
Oh... unfortunately it only worked in dartium, and not Chrome.

**Comment by a14n** [comment]
Actually, there's a generator that does use `source_gen` to generate files. Thegenerated files depend on [lib/js_wrapping.dart](https://github.com/a14n/dart-js-wrapping/blob/master/lib/js_wrapping.dart) but don't need `source_gen` to work.
`google_maps` has been generated with `source_gen` but the package can be used without this `source_gen` dependency.

**Comment by a14n** [comment]
I just tried https://github.com/a14n/dart-google-maps/tree/master/example/01-basics/map-simple and removing the `packages/source_gen` directory. It works with Dart 1.15.0.

**Comment by enyo** [comment]
When I try to compile to `js` I get

```
[Error from Dart2JS on exitlive|web/default.bootstrap.initialize.dart]:
packages/google_maps/src/core/map/map.dart:19:3:
External method without an implementation.
  external factory _GMap(Node mapDiv, [MapOptions opts]);
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Error from Dart2JS on exitlive|web/default.bootstrap.initialize.dart]:
packages/google_maps/src/core/map/map_options.dart:19:3:
External method without an implementation.
  external factory _MapOptions();
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Error from Dart2JS on exitlive|web/default.bootstrap.initialize.dart]:
packages/google_maps/src/core/controls/map_type_control_options.dart:19:3:
External method without an implementation.
  external factory _MapTypeControlOptions();
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by a14n** [comment]
What Dart version are you using ?

**Comment by enyo** [comment]
> Actually, there's a generator that does use source_gen to generate files. Thegenerated files depend on lib/js_wrapping.dart but don't need source_gen to work.
google_maps has been generated with source_gen but the package can be used without this source_gen dependency.

So the correct way would be to add `js_wrapping` as a dependency, and `source_gen` as a `dev_dependency`?

I'm using dart 1.15.

**Comment by a14n** [comment]
Not really because the generator (use in google_maps) need this transitionnal dependency. `dev_dependency` would make the generator only usable inside `js_wrapping` which is not what is needed.

**Comment by enyo** [comment]
Do you have any idea why it wouldn't work or what I could try?

**Comment by a14n** [comment]
Is your project public ? Do you have a URL ?

**Comment by enyo** [comment]
No unfortunately not.

**Comment by enyo** [comment]
Ok. So the problem was that I was using `google_maps` `3.0.0.` instead of `3.1.0`.

**Comment by enyo** [comment]
So, the problem was that we imported a server package in the client. :-/
