### ISSUE TITLE
Please upgrade source_gen dependency to ^0.5.0

### ISSUE THREAD

**Issue by domesticmouse** [a14n/dart-js-wrapping#9]
Hi Alexandre,

The out of date dependency of js_wrapping on source_gen 0.3.0 is blocking my app from upgrading to Angular2 2.0.0-beta.20. I forked and uplifted the dependency in js_wrapping myself, but I'm lost in the underlying source_gen API changes.

Halp?

**Comment by a14n** [comment]
Similar to #8 

Actually `source_gen` is only used to generate source files. So if you consume a lib that has been generated with `js_wrapping` you can simply add a `dependency_overrides` entry:

```yaml
dependency_overrides:
  source_gen: 0.5
```

**Comment by domesticmouse** [comment]
Thanks, works nicely!

**Comment by zoechi** [comment]
Perhaps js_wrapping could be split into a package that contains the part that the generated code also needs and the generator itself so that a package containing generated code doesn't depend on the generator and its dependencies.

**Comment by a14n** [comment]
Starting from `0.3.0` the package has been splitted in 2 parts (the dependency and the generator). There should not be conflict on `source_gen` dependency if you consume a package generated with `js_wrapping` (eg. `google_maps`)
